language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
- rm ./test/storage.json
before_install:
- openssl aes-256-cbc -K $encrypted_f94e9a91e820_key -iv $encrypted_f94e9a91e820_iv
  -in storage.json.enc -out ./test/storage.json -d
